#!/usr/bin/env bash
set -euo pipefail

readonly FD_GRAPHQL_FEATURES='issues_copilot_assignment_api_support,coding_agent_model_selection'
readonly FD_ASSIGN_MUTATION='mutation($issueId: ID!, $assigneeIds: [ID!]!, $repoId: ID!, $baseRef: String!, $customInstructions: String!, $customAgent: String!, $model: String!) { addAssigneesToAssignable(input: { assignableId: $issueId, assigneeIds: $assigneeIds, agentAssignment: { targetRepositoryId: $repoId, baseRef: $baseRef, customInstructions: $customInstructions, customAgent: $customAgent, model: $model } }) { assignable { ... on Issue { id assignees(first: 10) { nodes { login } } } } } }'
readonly FD_SUGGESTED_ACTORS_QUERY='query($owner: String!, $name: String!) { repository(owner: $owner, name: $name) { id suggestedActors(capabilities: [CAN_BE_ASSIGNED], first: 100) { nodes { login __typename ... on Bot { id } ... on User { id } } } } }'

fd_die() {
  echo "ERROR: $*" >&2
  return 1
}

fd_require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fd_die "Required command not found: $1"
}

fd_timestamp() {
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

fd_slug_to_label() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr '/. ' '-__'
}

fd_parent_label() {
  printf 'fleet-parent:%s' "$1"
}

fd_agent_label() {
  printf 'fleet-agent:%s' "$(fd_slug_to_label "$1")"
}

fd_pipeline_label() {
  printf 'fleet-dispatch'
}

fd_read_comments_markdown() {
  local comments_json="$1"
  jq -r '
    if length == 0 then ""
    else
      "## Comments and Discussion\n\n" + (
        to_entries
        | map(
            "### Comment \(.key + 1) by @\(.value.user.login // .value.author.login // .value.author // "unknown") (\(.value.created_at // .value.createdAt // ""))\n" + (.value.body // "")
          )
        | join("\n\n")
      )
    end
  ' <<<"$comments_json"
}

fd_clean_parent_body() {
  local body="$1"
  jq -nr --arg body "$body" '
    $body
    | gsub("\n---\\s*\n\\s*##\\s*🤖\\s*(Agent Pipeline|Agents Pipelines).*"; "")
    | gsub("\n---\\s*\n\\*Generated by AI.*?\\*\\s*$"; "")
    | rtrimstr("\n")
  '
}

fd_agent_description() {
  case "$1" in
    speckit.specify)
      printf '%s' 'Write a detailed specification for this feature. Analyze requirements, define acceptance criteria, and document the technical approach.'
      ;;
    speckit.plan)
      printf '%s' 'Create a detailed implementation plan. Break down the specification into actionable steps, identify dependencies, and define the order of execution.'
      ;;
    speckit.tasks)
      printf '%s' 'Generate granular implementation tasks from the plan. Each task should be a well-defined unit of work with clear inputs, outputs, and acceptance criteria.'
      ;;
    speckit.implement|copilot)
      printf '%s' 'Implement the requested changes. Write production-quality code with tests.'
      ;;
    speckit.analyze)
      printf '%s' 'Analyze the generated specification artifacts for consistency, coverage, ambiguity, and constitution compliance. This task is strictly read-only and should return an analysis report without modifying files.'
      ;;
    copilot-review)
      printf '%s' 'A Copilot code review has been requested on the main PR for this feature. This sub-issue tracks that review request and should be closed when the review is complete.'
      ;;
    *)
      printf 'Complete the work assigned to the `%s` agent.' "$1"
      ;;
  esac
}

fd_tailor_body_for_agent() {
  local parent_body="$1"
  local agent_slug="$2"
  local parent_issue_number="$3"
  local parent_title="$4"
  local clean_body
  clean_body="$(fd_clean_parent_body "$parent_body")"
  cat <<BODY
> **Parent Issue:** #${parent_issue_number} — ${parent_title}

## 🤖 Agent Task: \`${agent_slug}\`

$(fd_agent_description "$agent_slug")

---

## Parent Issue Context

${clean_body}

---
*Sub-issue created for agent \`${agent_slug}\` — see parent issue #${parent_issue_number} for full context*
BODY
}

fd_ensure_label() {
  local owner="$1"
  local repo="$2"
  local label="$3"
  gh label create "$label" --repo "$owner/$repo" --color '5319e7' --force >/dev/null 2>&1 || true
}

fd_validate_pipeline_config() {
  local config_path="$1"
  jq -e '
    .version == "1"
    and (.name | type == "string" and length > 0)
    and (.repository.owner | type == "string" and length > 0)
    and (.repository.name | type == "string" and length > 0)
    and (.defaults.baseRef | type == "string" and length > 0)
    and ((.defaults.errorStrategy == "fail-fast") or (.defaults.errorStrategy == "continue"))
    and (.defaults.pollIntervalSeconds | type == "number" and . >= 5)
    and (.defaults.taskTimeoutSeconds | type == "number" and . >= 5)
    and (.defaults.taskTimeoutSeconds >= .defaults.pollIntervalSeconds)
    and (.groups | type == "array" and length > 0)
    and all(.groups[];
      (.id | type == "string" and length > 0)
      and (.name | type == "string" and length > 0)
      and (.order | type == "number")
      and ((.executionMode == "serial") or (.executionMode == "parallel"))
      and (.agents | type == "array" and length > 0)
      and all(.agents[];
        (.slug | type == "string" and length > 0)
        and (.model | type == "string" and length > 0)
        and (.instructionTemplate | type == "string" and length > 0)
        and (.retryable | type == "boolean")
        and (.subIssue.title | type == "string" and length > 0)
        and (.subIssue.labels | type == "array" and length > 0)
      )
    )
  ' "$config_path" >/dev/null
}

fd_find_agent_in_config() {
  local config_path="$1"
  local agent_slug="$2"
  jq -c --arg slug "$agent_slug" '
    .groups[] as $group
    | $group.agents[]
    | select(.slug == $slug)
    | . + {
        groupId: $group.id,
        groupOrder: $group.order,
        executionMode: $group.executionMode,
        groupName: $group.name
      }
  ' "$config_path" | head -n 1
}

fd_group_ordered_json() {
  local config_path="$1"
  jq -c '.groups | sort_by(.order)[]' "$config_path"
}

fd_render_string_template() {
  local template="$1"
  local parent_issue_number="$2"
  local parent_title="$3"
  local agent_display_name="$4"
  local agent_slug="$5"
  local base_ref="$6"
  jq -nr \
    --arg template "$template" \
    --arg PARENT_ISSUE_NUMBER "$parent_issue_number" \
    --arg PARENT_ISSUE_TITLE "$parent_title" \
    --arg AGENT_DISPLAY_NAME "$agent_display_name" \
    --arg AGENT_SLUG "$agent_slug" \
    --arg BASE_REF "$base_ref" '
      $template
      | gsub("\\{\\{PARENT_ISSUE_NUMBER\\}\\}"; $PARENT_ISSUE_NUMBER)
      | gsub("\\{\\{PARENT_ISSUE_TITLE\\}\\}"; $PARENT_ISSUE_TITLE)
      | gsub("\\{\\{AGENT_DISPLAY_NAME\\}\\}"; $AGENT_DISPLAY_NAME)
      | gsub("\\{\\{AGENT_SLUG\\}\\}"; $AGENT_SLUG)
      | gsub("\\{\\{BASE_REF\\}\\}"; $BASE_REF)
    '
}

fd_template_path() {
  local repo_root="$1"
  local configured_path="$2"
  local absolute_path
  if [[ "$configured_path" = /* ]]; then
    absolute_path="$configured_path"
  else
    absolute_path="$repo_root/$configured_path"
  fi
  if [[ -f "$absolute_path" ]]; then
    printf '%s\n' "$absolute_path"
  else
    printf '%s\n' "$repo_root/solune/scripts/pipelines/templates/generic.md"
  fi
}

fd_render_template() {
  local template_path="$1"
  local issue_title="$2"
  local issue_body="$3"
  local issue_comments="$4"
  local parent_issue_number="$5"
  local parent_issue_url="$6"
  local base_ref="$7"
  local pr_branch="$8"
  local template
  template="$(cat "$template_path")"
  jq -nr \
    --arg template "$template" \
    --arg ISSUE_TITLE "$issue_title" \
    --arg ISSUE_BODY "$issue_body" \
    --arg ISSUE_COMMENTS "$issue_comments" \
    --arg PARENT_ISSUE_NUMBER "$parent_issue_number" \
    --arg PARENT_ISSUE_URL "$parent_issue_url" \
    --arg BASE_REF "$base_ref" \
    --arg PR_BRANCH "$pr_branch" '
      $template
      | gsub("\\{\\{ISSUE_TITLE\\}\\}"; $ISSUE_TITLE)
      | gsub("\\{\\{ISSUE_BODY\\}\\}"; $ISSUE_BODY)
      | gsub("\\{\\{ISSUE_COMMENTS\\}\\}"; $ISSUE_COMMENTS)
      | gsub("\\{\\{PARENT_ISSUE_NUMBER\\}\\}"; $PARENT_ISSUE_NUMBER)
      | gsub("\\{\\{PARENT_ISSUE_URL\\}\\}"; $PARENT_ISSUE_URL)
      | gsub("\\{\\{BASE_REF\\}\\}"; $BASE_REF)
      | gsub("\\{\\{PR_BRANCH\\}\\}"; $PR_BRANCH)
    '
}

fd_get_copilot_and_repo_ids() {
  local owner="$1"
  local repo="$2"
  local response
  response="$(gh api graphql \
    -H "GraphQL-Features: ${FD_GRAPHQL_FEATURES}" \
    -f query="$FD_SUGGESTED_ACTORS_QUERY" \
    -f owner="$owner" \
    -f name="$repo")"
  jq -c '
    .data.repository as $repo
    | {
        repoId: $repo.id,
        copilotId: ([ $repo.suggestedActors.nodes[] | select(.login == "copilot-swe-agent" and .__typename == "Bot") | .id ] | first)
      }
  ' <<<"$response"
}

fd_dispatch_graphql() {
  local issue_id="$1"
  local copilot_id="$2"
  local repo_id="$3"
  local base_ref="$4"
  local custom_agent="$5"
  local custom_instructions="$6"
  local model="$7"
  local payload
  payload="$(jq -n \
    --arg query "$FD_ASSIGN_MUTATION" \
    --arg issueId "$issue_id" \
    --arg assigneeId "$copilot_id" \
    --arg repoId "$repo_id" \
    --arg baseRef "$base_ref" \
    --arg customInstructions "$custom_instructions" \
    --arg customAgent "$custom_agent" \
    --arg model "$model" \
    '{
      query: $query,
      variables: {
        issueId: $issueId,
        assigneeIds: [$assigneeId],
        repoId: $repoId,
        baseRef: $baseRef,
        customInstructions: $customInstructions,
        customAgent: $customAgent,
        model: $model
      }
    }')"
  local attempt=1
  local output
  while true; do
    if output="$(gh api graphql -H "GraphQL-Features: ${FD_GRAPHQL_FEATURES}" --input - <<<"$payload" 2>&1)"; then
      printf '%s\n' "$output"
      return 0
    fi
    if [[ $attempt -ge 3 ]]; then
      echo "$output" >&2
      return 1
    fi
    if ! grep -qi 'rate limit' <<<"$output"; then
      echo "$output" >&2
      return 1
    fi
    sleep "$attempt"
    attempt=$((attempt + 1))
  done
}

fd_status_from_agent_task_state() {
  local normalized
  normalized="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr ' -' '__')"
  case "$normalized" in
    pending|queued)
      printf 'queued\n'
      ;;
    in_progress|running)
      printf 'in_progress\n'
      ;;
    completed|success|succeeded|done)
      printf 'completed\n'
      ;;
    failed|failure|error|cancelled|canceled)
      printf 'failed\n'
      ;;
    *)
      printf '%s\n' "$normalized"
      ;;
  esac
}

fd_resolve_task_for_agent() {
  local owner="$1"
  local repo="$2"
  local agent_slug="$3"
  local issue_title="$4"
  local tasks_json
  tasks_json="$(gh agent-task list --repo "$owner/$repo" --limit 100 --json id,name,state,createdAt,updatedAt,completedAt,pullRequestNumber,pullRequestUrl)"
  jq -r \
    --arg slug "$(printf '%s' "$agent_slug" | tr '[:upper:]' '[:lower:]')" \
    --arg title "$(printf '%s' "$issue_title" | tr '[:upper:]' '[:lower:]')" '
      . as $all
      | (
          map(
            select(
              ((.name // "") | ascii_downcase | contains($title))
              or ((.name // "") | ascii_downcase | contains($slug))
            )
          )
          | sort_by(.createdAt // "")
          | last
        ) // ($all | sort_by(.createdAt // "") | last) // empty
      | .id // empty
    ' <<<"$tasks_json"
}

fd_monitor_task() {
  local owner="$1"
  local repo="$2"
  local task_id="$3"
  local poll_interval="$4"
  local task_timeout="$5"
  local started_epoch="$6"
  local view_json task_state normalized_state now elapsed
  while true; do
    view_json="$(gh agent-task view "$task_id" --repo "$owner/$repo" --json id,name,state,createdAt,updatedAt,completedAt,pullRequestNumber,pullRequestUrl)"
    task_state="$(jq -r '.state // "queued"' <<<"$view_json")"
    normalized_state="$(fd_status_from_agent_task_state "$task_state")"
    if [[ "$normalized_state" == 'completed' || "$normalized_state" == 'failed' ]]; then
      jq -c --arg normalizedState "$normalized_state" '. + {normalizedState: $normalizedState}' <<<"$view_json"
      [[ "$normalized_state" == 'completed' ]]
      return
    fi
    now="$(date -u +%s)"
    elapsed=$((now - started_epoch))
    if (( elapsed >= task_timeout )); then
      jq -n --arg id "$task_id" --arg normalizedState 'timed_out' --arg completedAt "$(fd_timestamp)" '{id: $id, normalizedState: $normalizedState, completedAt: $completedAt}'
      return 1
    fi
    sleep "$poll_interval"
  done
}

fd_load_issue() {
  local owner="$1"
  local repo="$2"
  local issue_number="$3"
  gh api "repos/$owner/$repo/issues/$issue_number"
}

fd_load_issue_comments() {
  local owner="$1"
  local repo="$2"
  local issue_number="$3"
  gh api "repos/$owner/$repo/issues/$issue_number/comments?per_page=100"
}

fd_find_existing_sub_issue() {
  local owner="$1"
  local repo="$2"
  shift 2
  local labels_csv encoded_labels
  labels_csv="$(IFS=, ; printf '%s' "$*")"
  encoded_labels="$(jq -rn --arg labels "$labels_csv" '$labels|@uri')"
  gh api "repos/$owner/$repo/issues?state=all&per_page=100&labels=$encoded_labels" \
    | jq -c 'map(select(has("pull_request") | not)) | sort_by(.number) | .[0] // empty'
}

fd_create_sub_issue() {
  local owner="$1"
  local repo="$2"
  local title="$3"
  local body_file="$4"
  shift 4
  local args=(issue create --repo "$owner/$repo" --title "$title" --body-file "$body_file")
  local label
  for label in "$@"; do
    fd_ensure_label "$owner" "$repo" "$label"
    args+=(--label "$label")
  done
  local created_url issue_number
  created_url="$(gh "${args[@]}")"
  issue_number="${created_url##*/}"
  gh api "repos/$owner/$repo/issues/$issue_number"
}

fd_unassign_copilot() {
  local owner="$1"
  local repo="$2"
  local issue_number="$3"
  gh issue edit "$issue_number" --repo "$owner/$repo" --remove-assignee '@copilot' >/dev/null 2>&1 || true
}
