/**
 * Centralized Lucide icon barrel file.
 *
 * Every Lucide icon used in the application is re-exported from this single
 * module so imports stay consistent and auditable. Direct imports from
 * `lucide-react` are blocked by the ESLint `no-restricted-imports` rule in
 * eslint.config.js — add new icons here instead.
 *
 * Vite already tree-shakes unused exports, so this barrel file has zero
 * impact on bundle size.
 */

export {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDownUp,
  ArrowLeft,
  ArrowRightLeft,
  ArrowUpDown,
  ArrowUpRight,
  Ban,
  BarChart3,
  Bell,
  Bot,
  Boxes,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheckBig,
  ClipboardCopy,
  Clock,
  Columns3,
  Copy,
  Cpu,
  Crown,
  DollarSign,
  ExternalLink,
  FilePenLine,
  FileText,
  FileUp,
  Filter,
  GitBranch,
  GitMerge,
  GitPullRequest,
  HelpCircle,
  History,
  Image,
  Inbox,
  Info,
  Kanban,
  Layers,
  LayoutDashboard,
  Lightbulb,
  ListChecks,
  ListOrdered,
  Loader2,
  LoaderCircle,
  Lock,
  MessageSquare,
  Mic,
  MicOff,
  Monitor,
  Moon,
  MoonStar,
  Orbit,
  Package,
  PanelLeft,
  PanelLeftClose,
  Paperclip,
  Pencil,
  PencilLine,
  Play,
  PlayCircle,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShieldOff,
  Sparkles,
  Square,
  Sun,
  SunMedium,
  SunMoon,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Webhook,
  Workflow,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react';

export type { LucideIcon } from 'lucide-react';
