"""Minimal type stubs for the github-copilot-sdk package."""

from typing import Any

from copilot.types import CopilotClientOptions

class PermissionHandler:
    @staticmethod
    def approve_all(*args: Any, **kwargs: Any) -> Any: ...

class CopilotClient:
    def __init__(self, options: CopilotClientOptions) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def create_session(self, config: Any) -> Any: ...
