from typing import Any

from copilot.session import PermissionHandler as PermissionHandler

class CopilotClient:
    """GitHub Copilot SDK client for completions."""
    def __init__(self, **kwargs: Any) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def create_session(self, config: Any) -> Any: ...
    async def get_completion(self, **kwargs: Any) -> Any: ...
