"""Service for repository cleanup operations.

Provides preflight analysis, sequential execution, and audit trail for
deleting stale branches and closing stale PRs while preserving items
linked to open issues on the associated GitHub Project board.
"""
# pyright: basic
# reason: Legacy service module; pending follow-up typing pass.

from __future__ import annotations

import asyncio
import json
import re
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from enum import StrEnum
from typing import TYPE_CHECKING

import aiosqlite

from src.logging_utils import get_logger
from src.models.cleanup import (
    BranchInfo,
    CleanupAuditLogRow,
    CleanupExecuteRequest,
    CleanupExecuteResponse,
    CleanupHistoryResponse,
    CleanupItemResult,
    CleanupPreflightRequest,
    CleanupPreflightResponse,
    IssueInfo,
    OrphanedIssueInfo,
    PullRequestInfo,
)

if TYPE_CHECKING:
    from src.services.github_projects.service import GitHubProjectsService

logger = get_logger(__name__)


class ItemType(StrEnum):
    """Classification type for cleanup items."""

    BRANCH = "branch"
    PR = "pr"
    ISSUE = "issue"
    ORPHAN = "orphan"


class LinkMethod(StrEnum):
    """How an item was linked to an issue."""

    BRANCH_NAME = "branch_name"
    PR_BODY = "pr_body"
    OWNERSHIP = "ownership"


@dataclass(frozen=True)
class ItemClassification:
    """Result of classifying a branch/PR for cleanup linking."""

    item_type: ItemType
    linked_issue_number: int | None = None
    link_method: LinkMethod | None = None
    confidence: float = 0.0


# Delay between sequential deletion requests to respect GitHub secondary rate limits
DELETION_DELAY_SECONDS = 0.2

# Patterns for branch naming conventions that reference issue numbers
# Matches: issue-123, 123-feature-name, copilot/fix-123, etc.
ISSUE_NUMBER_PATTERNS = [
    re.compile(r"^(?:issue-?)(\d+)", re.IGNORECASE),
    re.compile(r"^(\d+)-"),
    re.compile(r"(?:^|/)(?:fix|close|resolve|feature|bug|hotfix)[/-](\d+)", re.IGNORECASE),
]

# Patterns for issue references in PR body text
# Matches: Closes #123, Fixes #123, Resolves #123, refs #123
PR_BODY_ISSUE_PATTERNS = [
    re.compile(r"(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)", re.IGNORECASE),
    re.compile(r"#(\d+)"),
]

# Labels that the app attaches to issues it creates.  Any open issue with one
# of these labels that is *not* on the project board is considered orphaned.
APP_CREATED_LABELS = frozenset(["ai-generated", "chore", "agent-config"])
APP_OWNED_BRANCH_PREFIXES = ("agent/", "chore/")
APP_OWNED_PR_TITLE_PREFIXES = (
    "add agent:",
    "remove agent:",
    "update agent:",
    "chore: add issue template",
    "chore: update",
)
APP_OWNED_PR_BODY_MARKERS = (
    "_auto-generated by chores feature._",
    "_auto-generated by inline chore editing._",
    "automatically generated by the agents section",
    "## agent:",
    "## remove agent:",
    "## update agent:",
)


def _extract_issue_numbers_from_branch(branch_name: str) -> list[int]:
    """Extract referenced issue numbers from a branch name using naming conventions."""
    numbers = []
    for pattern in ISSUE_NUMBER_PATTERNS:
        match = pattern.search(branch_name)
        if match:
            numbers.append(int(match.group(1)))
    return list(set(numbers))


def _extract_issue_numbers_from_text(text: str) -> list[int]:
    """Extract referenced issue numbers from PR body text."""
    if not text:
        return []
    numbers = [
        int(match.group(1))
        for pattern in PR_BODY_ISSUE_PATTERNS
        for match in pattern.finditer(text)
    ]
    return list(set(numbers))


def _references_app_created_issue(issue_numbers: list[int], app_issue_numbers: set[int]) -> bool:
    """Return True when any referenced issue belongs to a Solune-created issue set."""
    return any(issue_number in app_issue_numbers for issue_number in issue_numbers)


def _is_solune_owned_pr(pr: dict, app_issue_numbers: set[int]) -> bool:
    """Best-effort identification of PRs created by Solune-managed flows.

    The cleanup feature must be conservative: if a PR cannot be confidently
    identified as Solune-generated, it should be preserved.
    """
    head_branch = pr.get("head", {}).get("ref", "") or ""
    title = (pr.get("title") or "").strip().lower()
    body = pr.get("body") or ""
    body_lower = body.lower()
    has_owned_branch = head_branch.startswith(APP_OWNED_BRANCH_PREFIXES)
    has_owned_title = any(title.startswith(prefix) for prefix in APP_OWNED_PR_TITLE_PREFIXES)
    has_owned_body_marker = any(marker in body_lower for marker in APP_OWNED_PR_BODY_MARKERS)
    references_app_issue = _references_app_created_issue(
        _extract_issue_numbers_from_text(body), app_issue_numbers
    ) or _references_app_created_issue(
        _extract_issue_numbers_from_branch(head_branch), app_issue_numbers
    )

    if has_owned_branch:
        return True

    if has_owned_body_marker:
        return True

    if references_app_issue:
        return True

    # Title prefixes are only a supporting signal. On their own they are too generic
    # to safely classify a PR as Solune-generated.
    if has_owned_title and (has_owned_branch or has_owned_body_marker or references_app_issue):
        return True

    return False


def _is_solune_owned_branch(
    branch_name: str,
    prs_data: list[dict],
    app_issue_numbers: set[int],
) -> bool:
    """Best-effort identification of branches created by Solune-managed flows."""
    if branch_name.startswith(APP_OWNED_BRANCH_PREFIXES):
        return True

    if _references_app_created_issue(
        _extract_issue_numbers_from_branch(branch_name), app_issue_numbers
    ):
        return True

    for pr in prs_data:
        if pr.get("head", {}).get("ref") == branch_name and _is_solune_owned_pr(
            pr, app_issue_numbers
        ):
            return True

    return False


async def check_user_permission(
    github_service: GitHubProjectsService,
    access_token: str,
    owner: str,
    repo: str,
    username: str,
) -> tuple[bool, str | None]:
    """Check if the user has push access to the repository.

    Returns (has_permission, permission_error_message).
    """
    try:
        response = await github_service._rest_response(
            access_token,
            "GET",
            f"/repos/{owner}/{repo}/collaborators/{username}/permission",
        )
        if response.status_code == 200:
            data = response.json()
            permission = data.get("permission", "none")
            if permission in ("admin", "write", "maintain"):
                return True, None
            return False, (
                "You need at least push access to this repository "
                "to delete branches and close pull requests."
            )
        return False, f"Unable to verify permissions: HTTP {response.status_code}"  # noqa: TRY300 — reason: return in try block; acceptable for this pattern
    except Exception as e:  # noqa: BLE001 — reason: background cleanup; logs and continues
        logger.error("Permission check failed: %s", e)
        return False, f"Permission check failed: {e}"


async def fetch_all_branches(
    github_service: GitHubProjectsService,
    access_token: str,
    owner: str,
    repo: str,
) -> list[dict]:
    """Fetch all branches from the repository via REST API with pagination."""
    branches = []
    page = 1
    per_page = 100

    while True:
        response = await github_service._rest_response(
            access_token,
            "GET",
            f"/repos/{owner}/{repo}/branches",
            params={"per_page": per_page, "page": page},
        )
        if response.status_code != 200:
            logger.error(
                "Failed to fetch branches page %d: HTTP %d",
                page,
                response.status_code,
            )
            # For a destructive feature, partial preflight data is unsafe.
            # Raise instead of returning incomplete results that could
            # misclassify branches that should be preserved.
            raise RuntimeError(  # noqa: TRY003 — reason: domain exception with descriptive message
                f"Failed to fetch branches from GitHub: HTTP {response.status_code} on page {page}"
            )

        page_branches = response.json()
        if not page_branches:
            break

        branches.extend(page_branches)
        if len(page_branches) < per_page:
            break
        page += 1

    return branches


async def fetch_open_prs(
    github_service: GitHubProjectsService,
    access_token: str,
    owner: str,
    repo: str,
) -> list[dict]:
    """Fetch all open PRs from the repository via REST API with pagination."""
    prs = []
    page = 1
    per_page = 100

    while True:
        response = await github_service._rest_response(
            access_token,
            "GET",
            f"/repos/{owner}/{repo}/pulls",
            params={"state": "open", "per_page": per_page, "page": page},
        )
        if response.status_code != 200:
            logger.error(
                "Failed to fetch PRs page %d: HTTP %d",
                page,
                response.status_code,
            )
            # PR fetch failure is equally dangerous — branches that should
            # be preserved via PR body references could be incorrectly
            # slated for deletion.  Treat as a hard preflight failure.
            raise RuntimeError(  # noqa: TRY003 — reason: domain exception with descriptive message
                f"Failed to fetch pull requests from GitHub: HTTP {response.status_code} on page {page}"
            )

        page_prs = response.json()
        if not page_prs:
            break

        prs.extend(page_prs)
        if len(page_prs) < per_page:
            break
        page += 1

    return prs


async def fetch_open_issues_on_board(
    github_service: GitHubProjectsService,
    access_token: str,
    project_id: str,
) -> list[dict]:
    """Fetch open issues from the GitHub Project board via GraphQL.

    Returns list of dicts with 'number', 'title', 'repository' info.
    """
    query = """
    query($projectId: ID!, $first: Int!, $after: String) {
      node(id: $projectId) {
        ... on ProjectV2 {
          items(first: $first, after: $after, orderBy: {field: POSITION, direction: ASC}) {
            pageInfo { hasNextPage endCursor }
            nodes {
              content {
                ... on Issue {
                  number
                  title
                  state
                  repository { nameWithOwner }
                }
              }
            }
          }
        }
      }
    }
    """
    issues = []
    has_next = True
    after = None

    while has_next:
        data = await github_service._graphql(
            access_token,
            query,
            {"projectId": project_id, "first": 100, "after": after},
        )
        node = data.get("node")
        if not node:
            # An empty node means the project_id is invalid or
            # inaccessible.  If we silently return an empty issues list,
            # preflight will classify ALL non-main branches/PRs as
            # deletion candidates — extremely dangerous.  Fail loudly.
            raise RuntimeError(  # noqa: TRY003 — reason: domain exception with descriptive message
                "Failed to fetch project board issues: GraphQL returned no node. "
                "The project_id may be invalid or inaccessible."
            )

        items_data = node.get("items", {})
        page_info = items_data.get("pageInfo", {})
        has_next = page_info.get("hasNextPage", False)
        after = page_info.get("endCursor")

        for item in items_data.get("nodes", []):
            content = item.get("content") if item else None
            if not content:
                continue
            # Only include open issues (not PRs, not closed issues)
            if content.get("state") == "OPEN" and content.get("number") is not None:
                issues.append(content)

    return issues


async def fetch_app_created_open_issues(
    github_service: GitHubProjectsService,
    access_token: str,
    owner: str,
    repo: str,
) -> list[dict]:
    """Fetch all open issues in the repo that carry an app-created label.

    Uses the repository ``/issues`` listing endpoint with the ``labels`` query
    parameter to find open issues labeled with any of the ``APP_CREATED_LABELS``.
    Results are paginated to handle large result sets.  Since the ``/issues``
    endpoint also returns pull requests, these are filtered out, and issues
    are de-duplicated in case they carry multiple app-created labels.
    """
    issues: list[dict] = []

    for label in sorted(APP_CREATED_LABELS):
        page = 1
        per_page = 100
        while True:
            response = await github_service._rest_response(
                access_token,
                "GET",
                f"/repos/{owner}/{repo}/issues",
                params={"state": "open", "labels": label, "per_page": per_page, "page": page},
            )
            if response.status_code != 200:
                logger.error(
                    "Failed to fetch app-created issues (label=%s) page %d: HTTP %d",
                    label,
                    page,
                    response.status_code,
                )
                raise RuntimeError(  # noqa: TRY003 — reason: domain exception with descriptive message
                    f"Failed to fetch app-created issues from GitHub: "
                    f"HTTP {response.status_code} on page {page} for label '{label}'"
                )

            page_issues = response.json()
            if not page_issues:
                break

            # REST /issues also returns PRs — filter them out
            issues.extend(issue for issue in page_issues if "pull_request" not in issue)

            if len(page_issues) < per_page:
                break
            page += 1

    # De-duplicate (an issue may carry multiple app labels)
    seen: set[int] = set()
    unique: list[dict] = []
    for issue in issues:
        num = issue.get("number")
        if num is not None and num not in seen:
            seen.add(num)
            unique.append(issue)
    return unique


async def fetch_all_open_issues(
    github_service: GitHubProjectsService,
    access_token: str,
    owner: str,
    repo: str,
) -> list[dict]:
    """Fetch all open issues in the repository via REST API with pagination.

    Returns full issue dicts (excluding pull requests which the REST endpoint
    also returns).  Used to surface *every* open issue in the cleanup modal
    so users have full visibility.
    """
    issues: list[dict] = []
    page = 1
    per_page = 100

    while True:
        response = await github_service._rest_response(
            access_token,
            "GET",
            f"/repos/{owner}/{repo}/issues",
            params={"state": "open", "per_page": per_page, "page": page},
        )
        if response.status_code != 200:
            logger.warning(
                "Failed to fetch all open issues page %d: HTTP %d",
                page,
                response.status_code,
            )
            # Non-fatal: the preserve list is informational; orphaned list
            # and branch/PR lists remain authoritative.
            break

        page_items = response.json()
        if not page_items:
            break

        # REST /issues also returns PRs — filter them out
        issues.extend(item for item in page_items if "pull_request" not in item)

        if len(page_items) < per_page:
            break
        page += 1

    return issues


async def fetch_parent_issue_states(
    github_service: GitHubProjectsService,
    access_token: str,
    owner: str,
    repo: str,
    issue_numbers: list[int],
) -> dict[int, dict | None]:
    """For each issue number return its parent issue info via GraphQL, or None.

    Uses aliased batch queries (up to 20 issues per request) to avoid hitting
    GraphQL complexity limits.  If the ``parent`` field is unavailable or the
    query fails the function returns ``None`` for each affected issue — the
    caller must treat missing info conservatively (i.e. never delete on doubt).

    Returns a dict mapping ``issue_number`` → ``{"number": int, "state": str,
    "title": str}`` when a parent exists, or ``None`` when the issue has no
    parent or is not a sub-issue.
    """
    if not issue_numbers:
        return {}

    results: dict[int, dict | None] = {}
    BATCH_SIZE = 20

    for i in range(0, len(issue_numbers), BATCH_SIZE):
        batch = issue_numbers[i : i + BATCH_SIZE]
        alias_fields = "\n            ".join(
            f"i_{num}: issue(number: {num}) {{ parent {{ number state title }} }}" for num in batch
        )
        query = f"""
        query BatchParentIssues($owner: String!, $repo: String!) {{
          repository(owner: $owner, name: $repo) {{
            {alias_fields}
          }}
        }}
        """
        try:
            data = await github_service._graphql(
                access_token,
                query,
                {"owner": owner, "repo": repo},
            )
            repo_node = (data or {}).get("repository") or {}
            for num in batch:
                issue_data = repo_node.get(f"i_{num}")
                if issue_data is None:
                    results[num] = None
                    continue
                results[num] = issue_data.get("parent")  # None when no parent
        except Exception as e:  # noqa: BLE001 — reason: background cleanup; logs and continues
            logger.warning(
                "Failed to fetch parent issue states for batch starting at index %d: %s",
                i,
                e,
            )
            for num in batch:
                results[num] = None

    return results


def _categorize_branch(
    branch_data: dict,
    open_issue_numbers: set[int],
    issue_titles: dict[int, str],
    app_issue_numbers: set[int],
    app_sub_issue_closed_parent: dict[int, dict],
    prs_data: list[dict],
) -> BranchInfo:
    """Categorize a single branch as eligible for deletion or preservation."""
    name = branch_data.get("name", "")

    if name == "main":
        return BranchInfo(
            name=name, eligible_for_deletion=False, preservation_reason="Default protected branch"
        )

    # Strategy 1: link by branch naming convention
    referenced_issues = _extract_issue_numbers_from_branch(name)
    linked_issue = None
    linking_method = None
    for issue_num in referenced_issues:
        if issue_num in open_issue_numbers:
            linked_issue = issue_num
            linking_method = "naming_convention"
            break

    if linked_issue is not None:
        closed_parent = app_sub_issue_closed_parent.get(linked_issue)
        if closed_parent:
            return BranchInfo(
                name=name,
                eligible_for_deletion=True,
                linked_issue_number=linked_issue,
                linked_issue_title=issue_titles.get(linked_issue),
                linking_method=linking_method,
                deletion_reason=f"Sub-issue #{linked_issue} — parent issue #{closed_parent.get('number', '?')} has been closed",
            )
        return BranchInfo(
            name=name,
            eligible_for_deletion=False,
            linked_issue_number=linked_issue,
            linked_issue_title=issue_titles.get(linked_issue),
            linking_method=linking_method,
            preservation_reason=f"Linked to open issue #{linked_issue} on project board",
        )

    # Strategy 2: link by PR body reference
    for pr in prs_data:
        if pr.get("head", {}).get("ref") == name:
            pr_body = pr.get("body") or ""
            pr_issue_refs = _extract_issue_numbers_from_text(pr_body)
            for ref_num in pr_issue_refs:
                if ref_num in open_issue_numbers:
                    linked_issue = ref_num
                    linking_method = "pr_reference"
                    break
            if linked_issue:
                break

    if linked_issue is not None:
        closed_parent = app_sub_issue_closed_parent.get(linked_issue)
        if closed_parent:
            return BranchInfo(
                name=name,
                eligible_for_deletion=True,
                linked_issue_number=linked_issue,
                linked_issue_title=issue_titles.get(linked_issue),
                linking_method="pr_reference",
                deletion_reason=f"Sub-issue #{linked_issue} — parent issue #{closed_parent.get('number', '?')} has been closed",
            )
        return BranchInfo(
            name=name,
            eligible_for_deletion=False,
            linked_issue_number=linked_issue,
            linked_issue_title=issue_titles.get(linked_issue),
            linking_method=linking_method,
            preservation_reason=f"Linked to open issue #{linked_issue} via PR reference",
        )

    # Strategy 3: link by ownership
    if _is_solune_owned_branch(name, prs_data, app_issue_numbers):
        deletion_reason: str | None = None
        for ref_num in _extract_issue_numbers_from_branch(name):
            closed_parent = app_sub_issue_closed_parent.get(ref_num)
            if closed_parent:
                deletion_reason = f"Sub-issue #{ref_num} — parent issue #{closed_parent.get('number', '?')} has been closed"
                break
        return BranchInfo(name=name, eligible_for_deletion=True, deletion_reason=deletion_reason)

    return BranchInfo(
        name=name,
        eligible_for_deletion=False,
        preservation_reason="Not recognized as a Solune-generated asset",
    )


def _categorize_pr(
    pr: dict,
    open_issue_numbers: set[int],
    app_issue_numbers: set[int],
    app_sub_issue_closed_parent: dict[int, dict],
    preserved_branch_names: set[str],
    branches_to_delete: list[BranchInfo],
) -> PullRequestInfo:
    """Categorize a single PR as eligible for closing or preservation."""
    pr_number = pr.get("number", 0)
    pr_title = pr.get("title", "")
    head_branch = pr.get("head", {}).get("ref", "")
    pr_body = pr.get("body") or ""
    referenced = _extract_issue_numbers_from_text(pr_body)
    pr_is_solune_owned = _is_solune_owned_pr(pr, app_issue_numbers)

    # Check if any referenced issue is on the board
    linked_issue = None
    for ref_num in referenced:
        if ref_num in open_issue_numbers:
            linked_issue = ref_num
            break

    if linked_issue is not None:
        closed_parent = app_sub_issue_closed_parent.get(linked_issue)
        if closed_parent and pr_is_solune_owned:
            return PullRequestInfo(
                number=pr_number,
                title=pr_title,
                head_branch=head_branch,
                referenced_issues=referenced,
                eligible_for_deletion=True,
                deletion_reason=f"Sub-issue #{linked_issue} — parent issue #{closed_parent.get('number', '?')} has been closed",
            )
        return PullRequestInfo(
            number=pr_number,
            title=pr_title,
            head_branch=head_branch,
            referenced_issues=referenced,
            eligible_for_deletion=False,
            preservation_reason=f"References open issue #{linked_issue} on project board",
        )

    branch_preserved = head_branch in preserved_branch_names
    if branch_preserved:
        return PullRequestInfo(
            number=pr_number,
            title=pr_title,
            head_branch=head_branch,
            referenced_issues=referenced,
            eligible_for_deletion=False,
            preservation_reason=f"Head branch '{head_branch}' is linked to an open issue",
        )

    if not pr_is_solune_owned:
        return PullRequestInfo(
            number=pr_number,
            title=pr_title,
            head_branch=head_branch,
            referenced_issues=referenced,
            eligible_for_deletion=False,
            preservation_reason="Not recognized as a Solune-generated asset",
        )

    pr_deletion_reason: str | None = None
    for ref_num in referenced:
        closed_parent = app_sub_issue_closed_parent.get(ref_num)
        if closed_parent:
            pr_deletion_reason = f"Sub-issue #{ref_num} — parent issue #{closed_parent.get('number', '?')} has been closed"
            break
    return PullRequestInfo(
        number=pr_number,
        title=pr_title,
        head_branch=head_branch,
        referenced_issues=referenced,
        eligible_for_deletion=True,
        deletion_reason=pr_deletion_reason,
    )


async def preflight(
    github_service: GitHubProjectsService,
    access_token: str,
    username: str,
    request: CleanupPreflightRequest,
) -> CleanupPreflightResponse:
    """Perform a preflight check for the cleanup operation.

    Fetches all branches, open PRs, and open issues on the project board.
    Cross-references to determine which items to delete and which to preserve.
    """
    owner = request.owner
    repo = request.repo

    # 1. Check user permissions
    has_permission, permission_error = await check_user_permission(
        github_service, access_token, owner, repo, username
    )
    if not has_permission:
        return CleanupPreflightResponse(
            branches_to_delete=[],
            branches_to_preserve=[],
            prs_to_close=[],
            prs_to_preserve=[],
            open_issues_on_board=0,
            has_permission=False,
            permission_error=permission_error,
        )

    # 2. Fetch all data concurrently
    branches_data, prs_data, board_issues, app_issues, all_open_issues = await asyncio.gather(
        fetch_all_branches(github_service, access_token, owner, repo),
        fetch_open_prs(github_service, access_token, owner, repo),
        fetch_open_issues_on_board(github_service, access_token, request.project_id),
        fetch_app_created_open_issues(github_service, access_token, owner, repo),
        fetch_all_open_issues(github_service, access_token, owner, repo),
    )

    # 3. Build set of open issue numbers on the project board
    open_issue_numbers: set[int] = set()
    issue_titles: dict[int, str] = {}
    for issue in board_issues:
        num = issue.get("number")
        if num is not None:
            open_issue_numbers.add(num)
            issue_titles[num] = issue.get("title", "")

    app_issue_numbers: set[int] = set()
    for issue in app_issues:
        num = issue.get("number")
        if num is not None:
            app_issue_numbers.add(num)

    # 3b. Fetch parent-issue state for all app-created issues concurrently.
    #     Sub-issues of a closed parent are candidates for cleanup even when
    #     the sub-issue itself is still open/on the board.
    raw_parent_states = await fetch_parent_issue_states(
        github_service,
        access_token,
        owner,
        repo,
        list(app_issue_numbers),
    )
    # Map: app sub-issue number → parent info dict  (only closed parents)
    app_sub_issue_closed_parent: dict[int, dict] = {
        issue_num: parent
        for issue_num, parent in raw_parent_states.items()
        if parent and str(parent.get("state", "")).upper() == "CLOSED"
    }

    # 4. Categorize branches
    # Use asyncio.to_thread for large batches to avoid blocking the event loop
    # with CPU-bound regex matching.
    def _classify_branches() -> tuple[list[BranchInfo], list[BranchInfo]]:
        to_delete: list[BranchInfo] = []
        to_preserve: list[BranchInfo] = []
        for branch_data in branches_data:
            info = _categorize_branch(
                branch_data,
                open_issue_numbers,
                issue_titles,
                app_issue_numbers,
                app_sub_issue_closed_parent,
                prs_data,
            )
            if info.eligible_for_deletion:
                to_delete.append(info)
            else:
                to_preserve.append(info)
        return to_delete, to_preserve

    if len(branches_data) > 100:
        branches_to_delete, branches_to_preserve = await asyncio.to_thread(_classify_branches)
    else:
        branches_to_delete, branches_to_preserve = _classify_branches()

    # 5. Categorize PRs
    preserved_branch_names = {b.name for b in branches_to_preserve}

    def _classify_prs() -> tuple[list[PullRequestInfo], list[PullRequestInfo]]:
        to_close: list[PullRequestInfo] = []
        to_keep: list[PullRequestInfo] = []
        for pr in prs_data:
            info = _categorize_pr(
                pr,
                open_issue_numbers,
                app_issue_numbers,
                app_sub_issue_closed_parent,
                preserved_branch_names,
                branches_to_delete,
            )
            if info.eligible_for_deletion:
                to_close.append(info)
            else:
                to_keep.append(info)
        return to_close, to_keep

    if len(prs_data) > 100:
        prs_to_close, prs_to_preserve = await asyncio.to_thread(_classify_prs)
    else:
        prs_to_close, prs_to_preserve = _classify_prs()

    # 6. Identify orphaned app-created issues (open, labelled by app, not on board)
    orphaned_issues: list[OrphanedIssueInfo] = []
    orphaned_issue_numbers: set[int] = set()
    for issue in app_issues:
        issue_number = issue.get("number")
        if issue_number is not None and issue_number not in open_issue_numbers:
            issue_labels = [
                lbl.get("name", "") if isinstance(lbl, dict) else str(lbl)
                for lbl in issue.get("labels", [])
            ]
            orphaned_issues.append(
                OrphanedIssueInfo(
                    number=issue_number,
                    title=issue.get("title", ""),
                    labels=issue_labels,
                    html_url=issue.get("html_url"),
                    node_id=issue.get("node_id"),
                )
            )
            orphaned_issue_numbers.add(issue_number)

    # 7. Build issues_to_preserve — all open issues NOT already in the orphaned list.
    #    This ensures every open issue surfaces in the cleanup modal (defaulting to
    #    "don't delete") so users have full visibility.
    issues_to_preserve: list[IssueInfo] = []
    for issue in all_open_issues:
        issue_number = issue.get("number")
        if issue_number is None or issue_number in orphaned_issue_numbers:
            continue
        issue_labels = [
            lbl.get("name", "") if isinstance(lbl, dict) else str(lbl)
            for lbl in issue.get("labels", [])
        ]
        if issue_number in open_issue_numbers:
            reason = "Active on project board"
        elif any(lbl in APP_CREATED_LABELS for lbl in issue_labels):
            reason = "App-created issue (not on project board)"
        else:
            reason = "Not recognized as a Solune-generated asset"
        issues_to_preserve.append(
            IssueInfo(
                number=issue_number,
                title=issue.get("title", ""),
                labels=issue_labels,
                html_url=issue.get("html_url"),
                node_id=issue.get("node_id"),
                preservation_reason=reason,
            )
        )

    return CleanupPreflightResponse(
        branches_to_delete=branches_to_delete,
        branches_to_preserve=branches_to_preserve,
        prs_to_close=prs_to_close,
        prs_to_preserve=prs_to_preserve,
        orphaned_issues=orphaned_issues,
        issues_to_preserve=issues_to_preserve,
        open_issues_on_board=len(open_issue_numbers),
        has_permission=True,
        permission_error=None,
    )


async def execute_cleanup(
    github_service: GitHubProjectsService,
    access_token: str,
    owner: str,
    repo: str,
    request: CleanupExecuteRequest,
    db: aiosqlite.Connection,
    github_user_id: str,
) -> CleanupExecuteResponse:
    """Execute the cleanup operation: delete branches and close PRs sequentially.

    Creates an audit log entry, executes deletions, and updates the audit log.
    """
    operation_id = str(uuid.uuid4())
    started_at = datetime.now(UTC).isoformat()

    # Create audit log entry
    await db.execute(
        """INSERT INTO cleanup_audit_logs
        (id, github_user_id, owner, repo, project_id, started_at, status)
        VALUES (?, ?, ?, ?, ?, ?, 'in_progress')""",
        (operation_id, github_user_id, owner, repo, request.project_id, started_at),
    )
    await db.commit()

    results: list[CleanupItemResult] = []
    errors: list[CleanupItemResult] = []
    branches_deleted = 0
    prs_closed = 0

    # Delete branches sequentially
    for branch_name in request.branches_to_delete:
        # Server-side rejection of main branch
        if branch_name == "main":
            item = CleanupItemResult(
                item_type="branch",
                identifier=branch_name,
                action="failed",
                error="Cannot delete the main branch",
            )
            results.append(item)
            errors.append(item)
            continue

        try:
            success = await github_service.delete_branch(access_token, owner, repo, branch_name)
            if success:
                results.append(
                    CleanupItemResult(
                        item_type="branch",
                        identifier=branch_name,
                        action="deleted",
                    )
                )
                branches_deleted += 1
            else:
                item = CleanupItemResult(
                    item_type="branch",
                    identifier=branch_name,
                    action="failed",
                    error="Deletion failed — branch may be protected or already deleted",
                )
                results.append(item)
                errors.append(item)
        except Exception as e:
            logger.error("Failed to delete branch %s: %s", branch_name, e, exc_info=True)
            item = CleanupItemResult(
                item_type="branch",
                identifier=branch_name,
                action="failed",
                error="Deletion failed due to an unexpected error",
            )
            results.append(item)
            errors.append(item)

        # Rate limit delay
        await asyncio.sleep(DELETION_DELAY_SECONDS)

    # Close PRs sequentially
    for pr_number in request.prs_to_close:
        try:
            response = await github_service._rest_response(
                access_token,
                "PATCH",
                f"/repos/{owner}/{repo}/pulls/{pr_number}",
                json={"state": "closed"},
            )
            if response.status_code == 200:
                results.append(
                    CleanupItemResult(
                        item_type="pr",
                        identifier=str(pr_number),
                        action="closed",
                    )
                )
                prs_closed += 1
            else:
                item = CleanupItemResult(
                    item_type="pr",
                    identifier=str(pr_number),
                    action="failed",
                    error=f"HTTP {response.status_code}",
                )
                results.append(item)
                errors.append(item)
        except Exception as e:
            logger.error("Failed to close PR #%s: %s", pr_number, e, exc_info=True)
            item = CleanupItemResult(
                item_type="pr",
                identifier=str(pr_number),
                action="failed",
                error="Failed to close PR due to an unexpected error",
            )
            results.append(item)
            errors.append(item)

        # Rate limit delay
        await asyncio.sleep(DELETION_DELAY_SECONDS)

    # Delete orphaned app-created issues via GraphQL deleteIssue mutation
    issues_deleted = 0
    delete_issue_mutation = """
    mutation DeleteIssue($issueId: ID!) {
      deleteIssue(input: {issueId: $issueId}) {
        repository { id }
      }
    }
    """
    for issue_info in request.issues_to_delete:
        issue_number = issue_info.number
        node_id = issue_info.node_id
        try:
            await github_service._graphql(
                access_token,
                delete_issue_mutation,
                {"issueId": node_id},
            )
            results.append(
                CleanupItemResult(
                    item_type="issue",
                    identifier=str(issue_number),
                    action="deleted",
                )
            )
            issues_deleted += 1
        except Exception as e:  # noqa: BLE001 — reason: background cleanup; logs and continues
            logger.warning(
                "GraphQL deleteIssue failed for #%s (node_id=%s): %s — falling back to close",
                issue_number,
                node_id,
                e,
            )
            # Fallback: close the issue via REST if deletion is not permitted
            try:
                response = await github_service._rest_response(
                    access_token,
                    "PATCH",
                    f"/repos/{owner}/{repo}/issues/{issue_number}",
                    json={"state": "closed", "state_reason": "not_planned"},
                )
                if response.status_code == 200:
                    results.append(
                        CleanupItemResult(
                            item_type="issue",
                            identifier=str(issue_number),
                            action="deleted",
                        )
                    )
                    issues_deleted += 1
                else:
                    item = CleanupItemResult(
                        item_type="issue",
                        identifier=str(issue_number),
                        action="failed",
                        error=f"Failed to delete issue #{issue_number} (HTTP {response.status_code})",
                    )
                    results.append(item)
                    errors.append(item)
            except Exception as fallback_err:
                logger.exception(
                    "Fallback close also failed for issue #%s: %s", issue_number, fallback_err
                )
                item = CleanupItemResult(
                    item_type="issue",
                    identifier=str(issue_number),
                    action="failed",
                    error=f"Failed to delete issue #{issue_number} due to an internal error.",
                )
                results.append(item)
                errors.append(item)

        # Rate limit delay
        await asyncio.sleep(DELETION_DELAY_SECONDS)

    # Update audit log
    completed_at = datetime.now(UTC).isoformat()
    status = "completed" if not errors else "completed_with_errors"
    details_json = json.dumps({"results": [r.model_dump() for r in results]})

    branches_preserved = len([e for e in errors if e.item_type == "branch"])
    prs_preserved = len([e for e in errors if e.item_type == "pr"])
    # issues_failed tracked in errors list; no separate audit column yet
    _ = len([e for e in errors if e.item_type == "issue"])

    await db.execute(
        """UPDATE cleanup_audit_logs SET
        completed_at = ?, status = ?,
        branches_deleted = ?, branches_preserved = ?,
        prs_closed = ?, prs_preserved = ?,
        errors_count = ?, details = ?
        WHERE id = ?""",
        (
            completed_at,
            status,
            branches_deleted,
            branches_preserved,
            prs_closed,
            prs_preserved,
            len(errors),
            details_json,
            operation_id,
        ),
    )
    await db.commit()

    return CleanupExecuteResponse(
        operation_id=operation_id,
        branches_deleted=branches_deleted,
        branches_preserved=branches_preserved,
        prs_closed=prs_closed,
        prs_preserved=prs_preserved,
        issues_deleted=issues_deleted,
        errors=errors,
        results=results,
    )


async def get_cleanup_history(
    db: aiosqlite.Connection,
    github_user_id: str,
    owner: str,
    repo: str,
    limit: int = 10,
) -> CleanupHistoryResponse:
    """Retrieve audit trail of past cleanup operations."""
    cursor = await db.execute(
        """SELECT id, github_user_id, owner, repo, project_id,
        started_at, completed_at, status,
        branches_deleted, branches_preserved,
        prs_closed, prs_preserved,
        errors_count, details
        FROM cleanup_audit_logs
        WHERE github_user_id = ? AND owner = ? AND repo = ?
        ORDER BY started_at DESC LIMIT ?""",
        (github_user_id, owner, repo, limit),
    )
    rows = await cursor.fetchall()

    operations = []
    for row in rows:
        # details is stored as a JSON-encoded TEXT column in SQLite.
        # Parse it into a dict so the API response matches the contract
        # (frontend/contract expect a structured object, not a string).
        raw_details = row[13]
        parsed_details = None
        if raw_details:
            try:
                parsed_details = json.loads(raw_details)
            except (json.JSONDecodeError, TypeError):
                logger.warning("Failed to parse details JSON for audit log %s", row[0])
                parsed_details = None

        operations.append(
            CleanupAuditLogRow(
                id=row[0],
                github_user_id=row[1],
                owner=row[2],
                repo=row[3],
                project_id=row[4],
                started_at=row[5],
                completed_at=row[6],
                status=row[7],
                branches_deleted=row[8],
                branches_preserved=row[9],
                prs_closed=row[10],
                prs_preserved=row[11],
                errors_count=row[12],
                details=parsed_details,
            )
        )

    return CleanupHistoryResponse(operations=operations, count=len(operations))
