"""Template file service for new repository creation.

Reads `.github/`, `.specify/`, and `.gitignore` template files from a
configurable source directory and prepares them for committing to a new
GitHub repository.  The project-specific ``copilot-instructions.md`` is
replaced with a generic placeholder.
"""

from __future__ import annotations

import os
from pathlib import Path

from src.logging_utils import get_logger

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Generic copilot-instructions.md — hardcoded to guarantee genericity
# regardless of workspace state.
# ---------------------------------------------------------------------------

GENERIC_COPILOT_INSTRUCTIONS = """\
# Copilot Instructions

> This file was auto-generated by Solune. Customize it for your project.

## Tech Stack
<!-- TODO: List your primary languages, frameworks, and tools -->

## Coding Conventions
<!-- TODO: Describe naming conventions, code style, and patterns -->

## Testing
<!-- TODO: Describe testing approach, frameworks, and coverage expectations -->

## Deployment
<!-- TODO: Describe deployment process, environments, and CI/CD -->
"""

# Directories / files to bundle into a new repository.
_TEMPLATE_DIRS = (".github", ".specify")
_TEMPLATE_ROOT_FILES = (".gitignore",)

# File that should be replaced with the generic version.
_COPILOT_INSTRUCTIONS_BASENAME = "copilot-instructions.md"

# In-memory cache populated on first call.
_cached_files: list[dict[str, str]] | None = None
_cached_warnings: list[str] | None = None


def _is_safe_path(base: Path, target: Path) -> bool:
    """Return *True* when *target* is safely inside *base* (no traversal / symlinks)."""
    # os.path used intentionally — CodeQL recognises os.path.realpath+startswith
    # as a path-traversal sanitiser.
    real_base = os.path.realpath(str(base))
    real_target = os.path.realpath(str(target))
    return real_target.startswith(real_base + os.sep) or real_target == real_base


def _read_template_dir(source_dir: Path) -> tuple[list[dict[str, str]], list[str]]:
    """Walk the template source directory and return file entries.

    Each entry is ``{"path": "relative/path", "content": "…"}``.
    Symlinks and paths that escape the source directory are rejected.

    Returns:
        A tuple of ``(files, warnings)`` where *warnings* lists paths
        that could not be read.
    """
    files: list[dict[str, str]] = []
    warnings: list[str] = []

    for dir_name in _TEMPLATE_DIRS:
        dir_path = source_dir / dir_name
        if not dir_path.is_dir():
            logger.debug("Template directory %s not found, skipping", dir_path)
            continue
        for file_path in sorted(dir_path.rglob("*")):
            if not file_path.is_file():
                continue
            # Reject symlinks
            if file_path.is_symlink():
                logger.warning("Skipping symlink: %s", file_path)
                continue
            # Path traversal check
            if not _is_safe_path(source_dir, file_path):
                logger.warning("Skipping path-traversal candidate: %s", file_path)
                continue

            relative = file_path.relative_to(source_dir)
            # Replace copilot-instructions.md with the generic version
            if relative.name == _COPILOT_INSTRUCTIONS_BASENAME:
                content = GENERIC_COPILOT_INSTRUCTIONS
            else:
                try:
                    content = file_path.read_text(encoding="utf-8")
                except Exception:  # noqa: BLE001 — reason: best-effort operation; failure logged, execution continues
                    logger.warning("Could not read %s, skipping", file_path)
                    warnings.append(f"Failed to read template file: {relative}")
                    continue

            files.append({"path": str(relative), "content": content})

    # Root-level files (.gitignore, etc.)
    for root_file in _TEMPLATE_ROOT_FILES:
        file_path = source_dir / root_file
        if (
            file_path.is_file()
            and not file_path.is_symlink()
            and _is_safe_path(source_dir, file_path)
        ):
            try:
                content = file_path.read_text(encoding="utf-8")
                files.append({"path": root_file, "content": content})
            except Exception:  # noqa: BLE001 — reason: best-effort operation; failure logged, execution continues
                logger.warning("Could not read root template %s, skipping", root_file)
                warnings.append(f"Failed to read template file: {root_file}")

    return files, warnings


async def build_template_files(
    repo_name: str,
    display_name: str,
) -> tuple[list[dict[str, str]], list[str]]:
    """Build the list of template files for a new repository.

    Reads templates from ``TEMPLATE_SOURCE_DIR`` (env var) or falls back
    to the workspace root.  Results are cached after the first call.

    Returns:
        A tuple of ``(files, warnings)`` where *warnings* lists paths
        that could not be read.
    """
    global _cached_files, _cached_warnings

    if _cached_files is not None:
        return list(_cached_files), list(_cached_warnings or [])

    source_dir_env = os.environ.get("TEMPLATE_SOURCE_DIR", "")
    if source_dir_env:
        source_dir = Path(source_dir_env)
    else:
        # Fall back to workspace root (four levels up from this file:
        # services/ → src/ → backend/ → solune/ → repo root)
        source_dir = Path(__file__).resolve().parents[4]

    if not source_dir.is_dir():
        logger.warning("Template source directory %s does not exist", source_dir)
        return [], []

    files, warnings = _read_template_dir(source_dir)
    _cached_files = files
    _cached_warnings = warnings
    logger.info(
        "Loaded %d template files from %s for repo '%s' (%s)",
        len(files),
        source_dir,
        repo_name,
        display_name,
    )
    return list(files), warnings


def clear_template_cache() -> None:
    """Clear the in-memory template cache (useful for testing)."""
    global _cached_files, _cached_warnings
    _cached_files = None
    _cached_warnings = None
